<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="DataSourceManagerImpl" format="xml" hash="699259708">
    <data-source source="LOCAL" name="Django default" uuid="5f0a46b2-747d-4cd8-a0dc-278f4ac38080">
      <jdbc-driver>org.sqlite.JDBC</jdbc-driver>
      <jdbc-url>jdbc:sqlite:$PROJECT_DIR$/mybase.db</jdbc-url>
      <libraries>
        <library>
          <url>file://$USER_HOME$/.PyCharm30/config/jdbc-drivers/xerial-sqlite-license.txt</url>
        </library>
        <library>
          <url>file://$USER_HOME$/.PyCharm30/config/jdbc-drivers/sqlite-jdbc-3.7.6.3-20110609.081603-3.jar</url>
        </library>
      </libraries>
    </data-source>
    <data-source source="LOCAL" name="Django informatics" uuid="a57eb6aa-9f6a-4c97-9e97-f4a2dcbb5851">
      <jdbc-driver>com.mysql.jdbc.Driver</jdbc-driver>
      <jdbc-url>jdbc:mysql://informatics.mccme.ru/results_collector</jdbc-url>
      <user-name>shhdup</user-name>
      <user-password>dfc6dfcbdfc7dfc8dfcedfcbdfcedfcfdfc6dfdedfcb</user-password>
      <libraries>
        <library>
          <url>file://$USER_HOME$/.PyCharm30/config/jdbc-drivers/mysql-connector-license.txt</url>
        </library>
        <library>
          <url>jar://$USER_HOME$/.PyCharm30/config/jdbc-drivers/mysql-connector-java-5.1.26-bin.jar!/</url>
        </library>
      </libraries>
    </data-source>
  </component>
</project>

